config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('dean/', dean_home, name='dean_home'),
    path('teacher/', teacher_home, name='teacher_home'),
    path('student/', student_home, name='student_home'),
    path('logout/', logout_view, name='logout'),
    path('attendance/<int:pk>', group_attendance, name='group_attendance'),
]

main/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.core.validators import RegexValidator
from django.utils import timezone
from .generate_login import generate_numeric_login



# class Subject(models.Model):
#     name = models.CharField(max_length=50)


class BaseProfile(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField()
    gender = models.CharField(max_length=10, choices=[('male', 'Erkak'), ('female', 'Ayol')])
    image = models.FileField(upload_to='profile-photo', blank=True, null=True)
    password = models.CharField(max_length=30)
    login = models.CharField(
        max_length=12,
        unique=True,
        validators=[
            RegexValidator(
                regex=r'^\d{12}$',
                message="Login faqat 12 ta raqamdan iborat bo'lishi kerak."
            )
        ]
    )
    pasport = models.CharField(
        max_length=9,
        unique=True,
        validators=[
            RegexValidator(
                regex=r'^[A-Za-z]{2}\d{7}$',
                message="Pasport ma'lumotlari xato kiritildi. (N: AD1234567)"
            )
        ],)
    email = models.EmailField(max_length=254)
    phone = models.CharField(
        max_length=13,
        validators=[
            RegexValidator(
                regex=r'^\+998\d{9}$',
                message="Telefon raqami xato kiritildi. (N: +998901234567)"
            )
        ],
        unique=True
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.first_name
    
    def save(self, *args, **kwargs):
        if not self.login:
            code = generate_numeric_login()
            while Student.objects.filter(login=code).exists() or Teacher.objects.filter(login=code).exists():
                code = generate_numeric_login()
            self.login = code
        
        self.password = make_password(self.password)
        super().save(*args, **kwargs)



class Teacher(BaseProfile):
    # subjects = models.ManyToManyField(Subject)
    POSITIONS = [
        ('assistent', "O'qituvchi"),
        ('senior', "Katta o'qituvchi"),
        ('docent', "Dotsent (PhD)"),
        ('professor', 'Professor'),
        ('head_of_department', 'Kafedra mudiri'),
        ('dean', 'Fakultet dekani'),
    ]
    position = models.CharField(max_length=100, choices=POSITIONS)


class Group(models.Model):
    name = models.CharField(max_length=50)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name
    

class Student(BaseProfile):
    EDU_TYPES = [
        ('grant', 'Davlat granti asosida'),
        ('contract', 'To‘lov-kontrakt asosida'),
    ]
    edu_type = models.CharField(max_length=12, choices=EDU_TYPES)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, related_name='students')

    def attendance_percent(self):
        total = self.attendances.count()
        if total == 0:
            return 100
        present = self.attendances.filter(is_present=True).count()
        return round(present * 100 / total, 2)


class Attendance(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='attendances')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='group_attendances')
    marked_by = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True, blank=True, related_name='maked_attendances')
    is_present = models.BooleanField(default=False)
    grade = models.PositiveIntegerField(null=True, blank=True)
    date = models.DateField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.group and self.student:
            self.group = self.student.group
        super().save(*args, **kwargs)

    class Meta:
        unique_together = ('student', 'date')

    def __str__(self):
        return self.student.first_name

templates/home_page/attendance.html
{% extends "home_page/base.html" %}
{% load custom_filters %}
{% load static %}


{% block content %}
<!-- Table -->
<section class="table-container">
    <form method="post">
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Ism va Familiya</th>
                    <th>Baho</th>
                    <th>Davomat</th>
                    <th>Davomat (%)</th>
                    <th>Created By</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td class='student-name'><a href="">{{student.last_name}} {{student.first_name}}</a></td>
                    <td style="padding:0px;">
                        <input type="number" name="grade_{{ student.id }}" min="0" max="100" {% if attendance_dict %}value="{{ attendance_dict|default:''|get_item:student.id|default:''|get_attr:'grade' }}"{% endif %} maxlength="3" placeholder="_">
                    </td>
                    <td style="padding:0px;">
                        <input type="checkbox" name="present_{{ student.id }}" class="attendance-checkbox" {% if not attendance_dict or attendance_dict|get_item:student.id|get_attr:'is_present' %}checked{% endif %}>
                    </td>
                    <td>
                        <div class="progress-wrapper">
                            <progress value="{{ student.attendance_percent }}" max="100"></progress>
                            <span class="progress-text">{{ student.attendance_percent }}%</span>
                        </div>
                    </td>
                    <td>Qodirov J.</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="2" style="text-align:center;">
                        <input type="submit" value="Save" class="table-save-btn">
                    </td>
                    <td colspan="3" id="count-display"><b>N ta</b></td>
                </tr>
            </tbody>
        </table>
    </form>
</section>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/attendance.js' %}"></script>
{% endblock extra_js %}

templates/home_page/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Attendance System</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock extra_css %}
</head>
<body>
    <div class="container">
        <!-- Sidebar -->
        {% include "home_page/sidebar.html" %}

        <!-- Main Content -->
        <div class="main">
            <!-- Navbar -->
            {% include "home_page/navbar.html" %}

            <!-- Project Info -->
            <section class="project-info">
                <div>
                    <strong>Site Manager:</strong> Kevin Joseph<br>
                    <strong>Contact:</strong> +918050557558
                </div>
                <div>
                    <strong>Location:</strong> Bangalore<br>
                    <strong>Start Date:</strong> 01/02/2022<br>
                    <strong>Due Date:</strong> 01/12/2022
                </div>
            </section>

            <!-- Tabs -->
            <nav class="tabs">
                <button class="active">Tasks</button>
                <button>Topshiriqlar</button>
                <button>Drawings</button>
                <button>Issues</button>
                <button>Expenses</button>
                <button>Documents</button>
                <button>Invoice</button>
                <button>Labors Attendance</button>
                <button>Team Members</button>
            </nav>

            {% block content %}
            {% endblock content %}
        </div>
    </div>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    {% block extra_js %}
    {% endblock extra_js %}
</body>
</html>

templates/home_page/home.html
{% extends "home_page/base.html" %}
{% load static %}


{% block content %}
<!-- groups list -->
<section class="home-container">
    {% for group in groups %}
    <div class="group_list">
        <h3><a href="{% url "group_attendance" group.id %}">{{ group.name }}</a></h3><br>
        <p>Total Students: {{ group.students.count }}</p>
        <small><b>Start time:</b> 11-08-2025 | 10:00</small>
        <small><b>End time:</b> 11-08-2025 | 11:20</small>
    </div>
    {% endfor %}
</section>

{% if messages %}
<div class="messages" onclick="this.style.display='none'">
    {% for message in messages %}
        <div class="alert {{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/home.js' %}"></script>
{% endblock extra_js %}

templates/home_page/navbar.html
<!-- Navbar -->
<header class="navbar">
    <div class="dashboard">
        <button  class="menu-toggle" id="menuToggle"><i class="fas fa-bars"></i></button>
        <h3>Attendance System</h3>
    </div>
    <div class="user-info">
        <button class="menu-toggle" id="menuToggle2"><i class="fas fa-bars"></i></button>
        <span>O'zbekcha</span>
        <div class="cont">
            <div class="notification-badge">
                <i class="fas fa-bell"></i>
                <span class="badge">3</span>
            </div>
        </div>
        <div class="user-profile" id="userProfile">
            <img src="{{ user.image.url }}" alt="A" class="user-image">
            <div>
                <div class="item-1">{{ user.last_name|upper }} {{ user.first_name|slice:'1' }}.</div>
                {% if user.position %}
                    <div class="item-2">{{ user.get_position_display }}</div>
                {% else %}
                    <div class="item-2">{{ user.group.name|upper }}</div>
                {% endif %}
            </div>

            <div class="user-dropdown" id="userDropdown">
                <a href="">Profil</a>
                <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Chiqish</a>
            </div>
        </div>
    </div>
</header>

templates/home_page/sidebar.html
<!-- Sidebar -->
<aside class="sidebar" id="sidebar">
    <div class="sidebar-header">
        <h2 class="logo">BUILD 1.0</h2>
        <button class="close-btn" id="closeSidebar">×</button>
    </div>
    <ul class="menu">
        <li class="active"><i class=""></i> Dashboard</li>
        <li>Projects</li>
        <li>My Tasks <span class="badge">3</span></li>
        <li>Resources</li>
        <li>Budget</li>
        <li>Reporting <span class="badge">5</span></li>
        <li>Calendar</li>
        <li>Notification</li>
        <li class="active"><i class=""></i> Dashboard</li>
        <li>Projects</li>
        <li>My Tasks <span class="badge">3</span></li>
        <li>Resources</li>
        <li>Budget</li>
        <li>Reporting <span class="badge">5</span></li>
        <li>Calendar</li>
        <li>Notification</li>
    </ul>
    <div class="project-section">
        <h4>Projects</h4>
        <ul>
            <li class="active">Site Project - 1</li>
            <li>Site Project - 2</li>
        </ul>
    </div>
    <div class="support">
        <button>📞 Contact Support</button>
    </div>
</aside>